const traducao = {
    en: {
        "rodape": "ALL RIGHTS RESERVED BY DC COMICS",
        "tituloTestes": "TEST CATALOG",
        "menuRespostas": "ANSWERS",
        "menuContato": "CONTACT US",
        "menuInformacoes": "ABOUT",
        "tituloContato": "CONTACT US",
        "tituloPaginaPrincipal": "Winged Rat Collection",
        "tituloSugestaoMelhoriaContato": "Give us suggestions for improvement!",
        "descricaoAbaixoTituloSugestaoMelhoriaContato": "With Batman, there is no dialogue, but with us, there is. Tell us what you think!",
        "seusDadosContato": "Your Data",
        "placeholderNome": "Your Name",
        "placeholderEmail": "Your E-mail",
        "labelTituloMensagem": "Leave us a message:",
        "buttonEnviarMensagem": "Send",
        "tituloDesenvolvimentoPaginaInformacoes": "PAGE DEVELOPMENT",
        "descricaoDesenvolvimentoPagina": "The Winged Rat Collection was created with the purpose of recovering the content of the secret website featured in the movie “The Batman,” since after the film's release, the website stopped working, displaying only an image with the following phrase: “THE DOMAIN HAS BEEN SEIZED” (visit www.rataalada.com).",
        "descricaoPaginaIndexDesenvolvimento": "The home page contains the cards that, in theory, should lead to the first test and its solution. Unfortunately, it was not possible to do this, so I decided to leave it this way: just the cards.",
        "descricaoPaginaTheBatmanDesenvolvimento": "The “The Batman” page contains information about the movie “The Batman,” such as its synopsis, plot, and the cast that was part of the project. This section was created with the intention of showing where the initial idea for my website came from, as well as introducing the movie to users.",
        "descricaoPaginaRespostasDesenvolvimento": "The “Answers” page was created to have a mysterious tone. On the original movie website, as mentioned at the beginning, we are only shown an image warning us that the page has been taken over by the police of the fictional Gotham City. On my website, in the tab I describe here, I put the same image to say that it is impossible to know the answers to the tests, since the fictional police (who would be corrupt) do not want us to know the answers, as they expose an entire criminal scheme. There is no menu, since that part has already been taken over and does not “belong to me.”",
        "descricaoPaginaSobreDesenvolvimento": "Finally, the “About” page contains information about the complete development of the page, the website that was used as inspiration, and the references used for content.",
        "tituloSobreSiteOriginal": "About the original website",
        "descricaoSobreSiteOriginal": "www.rataalada.com is the name of a website used for a virtual marketing campaign for Matt Reeves' film The Batman. The website was launched on December 10, 2021, but content was only added to it on December 21, 2021. The website is in English and does not support Brazilian or European Portuguese. On December 20, 2021, a GIF image was added to DC Comics official Instagram account depicting a piece of paper with the words “let's play a game, just you and me” written on it. This is a reference to a phrase spoken by the character Riddler in the film. The next day, the website “www.rataalada.com” featured a riddle game themed around the antagonist of The Batman. The game consisted of a series of three questions where the player had to correctly answer the riddles posed by the character. Upon completion, an image of a Batman character card made by D.P.G.C. was released as a reward. Returning to the website later, the Riddler asked if the player had ever been to the Penguin's Iceberg Club. Regardless of the answers, the character states that it is best to stay away from there because the place looks more like a zoo, a reference to Batmans fight against the Penguin that takes place at the Iceberg Club in The Batman. The campaign continued until the film's opening week in March 2022, with six riddle tests and six questions about Gotham City. Finally, the last reward revealed a video about Bruce Waynes election campaign.The website was announced in the post-credits scene of The Batman movie. When accessing the website after March 5, 2022, a percentage countdown began, with all riddle games having ended. Upon reaching 100% on March 11, 2022, a file containing all the information the Riddler had collected about his main targets was made available. After the film's premiere, the website resumed operation with riddles on March 18, 2022, designed to announce a comic book written by Paul Dano, Riddler: Year One. Two more series of riddles were posted until the website was “shut down” by the D.P.G.C. at the end of the month. The website had a static background while the text was typed in green font, resembling a code reader. The website icon is the Riddler's question mark. After being taken over by the D.P.G.C., only the police logo on a blue background remained",
        "tituloReferencias": "References",
        "buttonPTBR": "Brazilian Portuguese",
        "tituloQuizFormsBatman": "🦇 QUIZ: Which Batman are you? 🦇",
        "primeiraPerguntaQuizBatman": "1. How do you deal with your feelings?",
        "segundaPerguntaQuizBatman": "2. What would be your favorite weapon as a hero?",
        "terceiraPerguntaQuizBatman": "3. What would your Batcave be like?",
        "quartaPerguntaQuizBatman": "4. How do people see you?",
        "quintaPerguntaQuizBatman": "5. Which of these phrases best describes you?",
        "sextaPerguntaQuizBatman": "6. What is your view about justice?",
        "resposta1QuizBatman": "a. I keep everything to myself and turn it into motivation", 
        "resposta2QuizBatman": "b. I try to rationalize and move on", 
        "resposta3QuizBatman": "c. I isolate myself, but feel everything intensely", 
        "resposta4QuizBatman": "d. I use sarcasm as a shield", 
        "resposta5QuizBatman": "e. I try to stay balanced and do what is right", 
        "resposta6QuizBatman": "a. Raw strength and intimidating stare", 
        "resposta7QuizBatman": "b. Cutting-edge technology and sophisticated armor", 
        "resposta8QuizBatman": "c. Agility and stealth tactics", 
        "resposta9QuizBatman": "d. Charm and improvisation", 
        "resposta10QuizBatman": "e. Discipline and training", 
        "resposta11QuizBatman": "a. Dark, gothic and full of secrets", 
        "resposta12QuizBatman": "b. Modern, functional and full of gadgets", 
        "resposta13QuizBatman": "c. Minimalist but efficient", 
        "resposta14QuizBatman": "d. A bit messy but stylish", 
        "resposta15QuizBatman": "e. Classic, with everything in order", 
        "resposta16QuizBatman": "a. Mysterious and intense", 
        "resposta17QuizBatman": "b. Serious and intelligent", 
        "resposta18QuizBatman": "c. Cold but deep", 
        "resposta19QuizBatman": "d. Charismatic and creative", 
        "resposta20QuizBatman": "e. Fair and reliable", 
        "resposta21QuizBatman": "a. \"Vengeance drives me.\"", 
        "resposta22QuizBatman": "b. \"I am Batman\"", 
        "resposta23QuizBatman": "c. \"I dont need people to like me, only to respect me.\"", 
        "resposta24QuizBatman": "d. \"Who said Batman cant have style?\"", 
        "resposta25QuizBatman": "e. \"With great power comes great responsibility\"", 
        "resposta26QuizBatman": "a. Justice is protecting innocents using intelligence.", 
        "resposta27QuizBatman": "b. Justice is eliminating evil firmly and without hesitation.", 
        "resposta28QuizBatman": "c. Justice is maintaining balance and inspiring hope.", 
        "resposta29QuizBatman": "d. Justice is confronting corruption where it truly begins.", 
        "resposta30QuizBatman": "e. Justice is being fair.",
        "tituloResultadosQuiz": "Results",
        "tituloPrimeiroResultado": "Majority A: Robert Pattinson (The Batman - 2022)",
        "tituloSegundoResultado": "Majority B: Christian Bale (The Dark Knight Trilogy - 2005 to 2012)",
        "tituloTerceiroResultado": "Majority C: Ben Affleck (Justice League, Batman vs Superman - from DCEU)",
        "tituloQuartoResultado": "Majority D: George Clooney or Val Kilmer (Batman and Robin, Batman Forever)",
        "descricaoPrimeiroResultado": "You are dark, introspective, and driven by deep emotions. You don't care what others think, because you are focused on your mission. You are still discovering yourself, but you already command respect.",
        "descricaoSegundoResultado": "You are determined, calculating, and intense. You masterfully balance your Bruce Wayne side with your Batman side. A true strategist, you play the long game.",
        "descricaoTerceiroResultado": "You are a weary but still powerful veteran. A little more bitter and cynical, you prefer action to words. You will go to any lengths if you believe you are right.",
        "descricaoQuartoResultado": "You are lighter, more stylish, and don't take yourself so seriously. Still, you have a sense of justice. You prefer to resolve issues with charm (and a Batmarca credit card,  maybe?).",
        "tituloPaginaRespostas": "Answers",
        "legendaInicialImagemBatman": "“I wish I could say I'm making a difference, but I don't know. Murders, robberies, assaults. Two years later, all of this. And now this... The city is consuming itself. Maybe there's no hope left.”",
        "tituloSinopseTheBatman": "Sinopsis",
        "descricaoSinopse": "Two years of roaming the streets as Batman (Robert Pattinson), striking fear into the hearts of criminals, have taken Bruce Wayne into the depths of Gotham City's shadows. With only a few trusted allies—Alfred Pennyworth (Andy Serkis), Lieutenant James Gordon (Jeffrey Wright)—among the corrupt network of authorities and important figures in the city, the lone vigilante established himself as the sole embodiment of vengeance among his fellow citizens. When a killer targets Gotham's elite with a series of sadistic machinations, a trail of cryptic clues sends the World's Greatest Detective on an investigation into the underworld, where he encounters characters such as Selina Kyle/aka Catwoman (Zoë Kravitz), Oswald Cobblechuck/aka the Penguin (Colin Farrell), Carmine Falcone (John Turturro), and Edward Nashton/aka the Riddler (Paul Dano). As the evidence begins to lead him closer to home and the scale of the perpetrator's plans becomes clear, Batman must forge new relationships, unmask the culprit, and bring justice to the abuse of power and corruption that have long plagued Gotham City.",
        "tituloTramaTheBatman": "PLOT",
        "descricaoTramaTheBatman": "On Halloween night, the mayor of Gotham is killed by a murderer named the Riddler, who leaves riddles for Batman. Bruce Wayne, who has been Batman for two years, investigates the case with Lieutenant Gordon. They discover that the Riddler is targeting public figures involved in corruption. Batman crosses paths with Selina Kyle (Catwoman), whose friend Annika disappeared after getting involved with corrupt politicians. Selina works at the Iceberg Lounge, controlled by Carmine Falcone, a powerful mobster who is also her father. During the investigation, District Attorney Colson is killed by the Riddler after refusing to reveal the name of an informant. The corruption revealed also involves the Wayne family's past. It is discovered that Thomas Wayne asked Falcone for help in silencing a journalist, but later wanted to redeem himself. Thomas and Martha ended up dead, and Bruce begins to suspect Falcone's involvement. Selina tries to kill Falcone for revenge, but Batman stops her. However, the Riddler murders him when he is arrested. Even after his capture, the Riddler reveals his final plan: to detonate bombs that will flood Gotham and encourage fanatical followers to kill the new mayor, Bella Reál. Batman and Selina prevent the attack, and Batman begins to act as a symbol of hope for the city. Selina decides to leave Gotham, and the two go their separate ways. Meanwhile, the Riddler finds a mysterious new ally in Arkham.",
        "tituloElencoTheBatman": "CAST",
        "RobertPattinson": "Robert Pattinson as Bruce Wayne/Batman",
        "ZoeKravitz": "Zoe Kravitz as CatWoman",
        "PaulDano": "Paul Dano as Riddler",
        "JeffreyWright": "Jeffrey Wright as Jim Gordon",
        "JohnTurturro": "John Turturro as Falcone",
        "ColinFarrell": "Colin Farrell as Penguin",

    }
};

function setLinguagem(en){ 
    document.querySelectorAll("[data-i18n]").forEach(mudar => {
        const chave = mudar.getAttribute("data-i18n");
        const novoTexto = traducao["en"][chave];
        mudar.textContent = novoTexto; 
    });
}