const traducao = {
    ptbr: {
        "rodape": "TODOS OS DIREITOS RESERVADOS À DC COMICS ©",
        "tituloTestes": "CATÁLOGO DE TESTES",
        "menuRespostas": "RESPOSTAS",
        "menuContato": "FALE CONOSCO",
        "menuInformacoes": "SOBRE",
        "tituloContato": "FALE CONOSCO",
        "tituloPaginaPrincipal": "Acervo Rata Alada",
        "tituloSugestaoMelhoriaContato": "Nos dê sugestões de melhoria!",
        "descricaoAbaixoTituloSugestaoMelhoriaContato": "Com o Batman não existe diálogo, mas conosco, existe. Conte-nos o que pensa!",
        "seusDadosContato": "Seus Dados:",
        "placeholderNome": "SEU NOME",
        "placeholderEmail": "SEU E-MAIL",
        "labelTituloMensagem": "Deixe-nos sua mensagem:",
        "buttonEnviarMensagem": "Enviar",
        "tituloDesenvolvimentoPaginaInformacoes": "DESENVOLVIMENTO DA PÁGINA",
        "descricaoDesenvolvimentoPagina": "O Acervo Rata Alada foi criado com a finalidade de resgatar o conteúdo do site secreto disponibilizado no filme 'The Batman', uma vez que após o lançamento do longa, o site parou de funcionar, apresentando apenas uma imagem com a seguinte frase: 'THE DOMAIN HAS BEEN SIZED' (acesse www.rataalada.com)",
        "descricaoPaginaIndexDesenvolvimento": "A página inicial contém os cards que, na teoria, deveriam levar para o primeiro teste e sua solução. Infelizmente não foi possível fazer isso, então optei por deixar dessa maneira: apenas os cards.",
        "descricaoPaginaTheBatmanDesenvolvimento": "A página 'The Batman' contém informações acerca do filme 'The Batman', como sua sinopse, sua trama e o elenco que fez parte do projeto. Essa sessão foi criada com a intenção de mostrar de onde surgiu a ideia inicial do meu site, além de apresentar o filme aos usuários.",
        "descricaoPaginaRespostasDesenvolvimento": "A página 'Respostas' foi criada para ter um tom misterioso. No site original do filme, como dito no início, nos é mostrada apenas uma imagem avisando que a página foi tomada pela polícia da cidade fictícia Gotham City. No meu site, na aba que descrevo aqui, coloquei a mesma imagem, para dizer que é impossível saber as respostas para os testes, uma vez que a polícia fictícia (que seria corrupta) não quer que saibamos das respostas, pois elas expõe todo um esquema criminoso. Não há menu, já que essa parte já foi tomada e não 'me pertence'.",
        "descricaoPaginaSobreDesenvolvimento": "Por fim, a página 'Sobre' contém informações sobre o desenvolvimento completo da página, sobre o site que foi utilizado como inspiração e as referências utilizadas para conteúdo.",
        "tituloSobreSiteOriginal": "SOBRE O SITE ORIGINAL",
        "descricaoSobreSiteOriginal": "www.rataalada.com é o nome de um site usado para uma campanha de marketing virtual do filme The Batman de Matt Reeves. O site foi aberto em 10 de dezembro de 2021,porém conteúdos só foram adicionados nele em 21 de dezembro de 2021. O site é em inglês, e não possui suporte para português brasileiro ou europeu. Em 20 de dezembro de 2021, uma imagem GIF foi adicionada na conta oficial da DC Comics no Instagram retratando um papel com as palavras escritas 'vamos jogar um jogo, só eu e você'. Uma referência a frase dita pelo personagem Charada no filme. No dia seguinte, o site 'www.rataalada.com passou a ter um jogo de charadas com temática do antagonista de The Batman. O jogo consistia em uma série de três perguntas onde o jogador deveria responder corretamente os enigmas feitos pelo personagem. Quando concluído, uma imagem de uma ficha do personagem Batman feita pelo D.P.G.C. era divulgada como recompensa. Voltando ao site mais tarde, uma pergunta era feita pelo Charada se o jogador já frequentou o Clube Iceberg do Pinguim. Independente das repostas, o personagem afirma que é melhor passar longe de lá pois o local mais parece um zoológico, uma referência ao combate de Batman contra o Pinguim que ocorre no Clube Iceberg em The Batman. A campanha continuou até a semana de estreia do filme, em março de 2022, com seis testes de charadas e seis perguntas sobre Gotham City. Por fim, a última recompensa revelava um vídeo sobre a campanha eleitoral de Bruce Wayne. O site foi divulgado no pós-crédito do filme The Batman.[1] Ao acessar o site após o dia 5 de março de 2022, uma contagem de porcentagem era iniciada, com todos os jogos de charadas tendo acabado. Ao chegar aos 100%, no dia 11 de março de 2022, um arquivo contendo todas as informações que o Charada recolheu sobre os seus principais alvos foi disponibilizado. Após a estreia do filme, o site voltou a funcionar com charadas em 18 de março de 2022, feito para anunciar uma história em quadrinhos escrita por Paul Dano, Riddler: Year One. Mais duas séries de charadas foram colocadas até o site ser 'fechado' pelo D.P.G.C. no final do mês. Layout O site era feito com uma estática constante de fundo enquanto o texto é digitado em uma fonte verde, se assemelhando a um leitor de código. O ícone do site é um ponto de interrogação do Charada. Após ser tomado pelo D.P.G.C., o apenas a logo da polícia num fundo azul permaneceu.",
        "tituloReferencias": "REFERÊNCIAS",
        "buttonPTBR": "Português Brasileiro",
        "tituloQuizFormsBatman": "🦇QUIZ: Qual Batman você é?🦇",
        "primeiraPerguntaQuizBatman": "1. Como você lida com seus sentimentos?", 
        "segundaPerguntaQuizBatman": "2. Qual seria sua arma favorita como herói?", 
        "terceiraPerguntaQuizBatman": "3. Como seria sua Batcaverna?", 
        "quartaPerguntaQuizBatman": "4. Como as pessoas te veem?", 
        "quintaPerguntaQuizBatman": "5. Qual dessas frases mais te representa?", 
        "sextaPerguntaQuizBatman": "6. Qual é sua visão sobre justiça?", 
        "resposta1QuizBatman": "a. Guardo tudo pra mim e transformo em motivação", 
        "resposta2QuizBatman": "b. Tento racionalizar e seguir em frente", 
        "resposta3QuizBatman": "c. Me isolo, mas sinto tudo com muita intensidade", 
        "resposta4QuizBatman": "d. Uso o sarcasmo como escudo", 
        "resposta5QuizBatman": "e. Tento manter o equilíbrio e fazer o que é certo", 
        "resposta6QuizBatman": "a. Força bruta e olhar intimidador", 
        "resposta7QuizBatman": "b. Tecnologia de ponta e armaduras sofisticadas", 
        "resposta8QuizBatman": "c. Agilidade e táticas furtivas", 
        "resposta9QuizBatman": "d. Charme e improviso", 
        "resposta10QuizBatman": "e. Disciplina e treinamento", 
        "resposta11QuizBatman": "a. Escura, gótica e cheia de segredos", 
        "resposta12QuizBatman": "b. Moderna, funcional e cheia de gadgets", 
        "resposta13QuizBatman": "c. Minimalista, mas eficiente", 
        "resposta14QuizBatman": "d. Um pouco bagunçada, mas estilosa", 
        "resposta15QuizBatman": "e. Clássica, com tudo em ordem", 
        "resposta16QuizBatman": "a. Misterioso e intenso", 
        "resposta17QuizBatman": "b. Sério e inteligente", 
        "resposta18QuizBatman": "c. Frio, mas profundo", 
        "resposta19QuizBatman": "d. Carismático e criativo", 
        "resposta20QuizBatman": "e. Justo e confiável", 
        "resposta21QuizBatman": "a. \"A vingança me guia.\"", 
        "resposta22QuizBatman": "b. \"Eu sou o Batman\"", 
        "resposta23QuizBatman": "c. \"Não preciso que gostem de mim, só que me respeitem.\"", 
        "resposta24QuizBatman": "d. \"Quem disse que o Batman não pode ter estilo?\"", 
        "resposta25QuizBatman": "e. \"Com grandes poderes vem grandes responsabilidades\"", 
        "resposta26QuizBatman": "a. Justiça é proteger inocentes usando inteligência.", 
        "resposta27QuizBatman": "b. Justiça é eliminar o mal com firmeza e sem hesitar.", 
        "resposta28QuizBatman": "c. Justiça é manter o equilíbrio e inspirar esperança.", 
        "resposta29QuizBatman": "d. Justiça é enfrentar a corrupção onde ela realmente nasce.", 
        "resposta30QuizBatman": "e. Justiça é ser justo.",
        "tituloResultadosQuiz": "Resultados",
        "tituloPrimeiroResultado": "🔴 Maioria A: Robert Pattinson (The Batman - 2022)",
        "tituloSegundoResultado": "🔵 Maioria B: Christian Bale (Trilogia Cavaleiro das Trevas - 2005 a 2012)",
        "tituloTerceiroResultado": "⚫ Maioria C: Ben Affleck (Batman vs Superman, Liga da Justiça)",
        "tituloQuartoResultado": "🟣 Maioria D: George Clooney ou Val Kilmer (Batman & Robin, Batman Eternamente)",
        "descricaoPrimeiroResultado": "Você é sombrio, introspectivo e movido por emoções profundas. Não se importa com o que pensam, pois está focado na sua missão. Ainda está se descobrindo, mas já impõe respeito.",
        "descricaoSegundoResultado": "Você é determinado, calculista e intenso. Equilibra seu lado Bruce Wayne com o de Batman com maestria. Um verdadeiro estrategista, que joga o jogo a longo prazo.",
        "descricaoTerceiroResultado": "Você é um veterano cansado, mas ainda poderoso. Um pouco mais amargo e cínico, prefere agir do que falar. Vai até as últimas consequências se achar que está certo.",
        "descricaoQuartoResultado": "Você é mais leve, estiloso e não se leva tão a sério. Ainda assim, tem senso de justiça. Prefere resolver com charme (e um cartão de crédito da Batmarca, talvez?).",
        "tituloPaginaRespostas": "Respostas",
        "legendaInicialImagemBatman": "'Gostaria de poder dizer que estou fazendo a diferença, mas não sei. Assassinatos, roubos, agressões. Dois anos depois, tudo isso. E agora isso... A cidade está se consumindo. Talvez não tenha mais salvação.' ― Batman",
        "tituloSinopseTheBatman": "SINOPSE",
        "descricaoSinopse": "Dois anos vagando pelas ruas como o Batman ( Robert Pattinson ), espalhando medo nos corações dos criminosos, levaram Bruce Wayne para as profundezas das sombras de Gotham City . Com apenas alguns aliados confiáveis ​​— Alfred Pennyworth ( Andy Serkis ), Tenente James Gordon ( Jeffrey Wright ) — entre a rede corrupta de autoridades e figuras importantes da cidade, o vigilante solitário se estabeleceu como a única personificação da vingança entre seus concidadãos. Quando um assassino mira a elite de Gotham com uma série de maquinações sádicas, uma trilha de pistas enigmáticas envia o Maior Detetive do Mundo em uma investigação no submundo, onde ele encontra personagens como Selina Kyle/também conhecida como Mulher-Gato ( Zoë Kravitz ), Oswald Cobb/também conhecido como Pinguim ( Colin Farrell ), Carmine Falcone ( John Turturro ) e Edward Nashton/também conhecido como Charada ( Paul Dano ). À medida que as evidências começam a levá-lo para mais perto de casa e a escala dos planos do perpetrador se torna clara, Batman deve forjar novos relacionamentos, desmascarar o culpado e trazer justiça ao abuso de poder e à corrupção que há muito tempo assolam Gotham City",
        "tituloTramaTheBatman": "TRAMA",
        "descricaoTramaTheBatman": "Na noite de Halloween, o prefeito de Gotham é morto por um assassino chamado Charada, que deixa enigmas para o Batman. Bruce Wayne, atuando como Batman há dois anos, investiga o caso com o tenente Gordon. Eles descobrem que o Charada está mirando figuras públicas envolvidas em corrupção. Batman cruza o caminho de Selina Kyle (Mulher-Gato), cuja amiga Annika desapareceu após se envolver com políticos corruptos. Selina trabalha no clube Iceberg Lounge, controlado por Carmine Falcone, um mafioso poderoso que também é pai dela. Durante a investigação, o promotor Colson é morto por Charada após se recusar a revelar o nome de um informante. A corrupção revelada envolve também o passado dos Wayne. Descobre-se que Thomas Wayne pediu ajuda a Falcone para silenciar um jornalista, mas depois quis se redimir. Thomas e Martha acabaram mortos, e Bruce passa a desconfiar do envolvimento de Falcone. Selina tenta matar Falcone por vingança, mas Batman a impede. No entanto, Charada o assassina ao ser preso. Mesmo capturado, Charada revela seu plano final: explodir bombas que inundam Gotham e incentivar seguidores fanáticos a matar a nova prefeita, Bella Reál. Batman e Selina impedem o atentado, e Batman começa a atuar como símbolo de esperança para a cidade. Selina decide deixar Gotham, e os dois seguem caminhos diferentes. Enquanto isso, o Charada encontra um novo aliado misterioso em Arkham.",
        "tituloElencoTheBatman": "ELENCO",
        "RobertPattinson": "Robert Pattinson como Bruce Wayne/Batman",
        "ZoeKravitz": "Zoe Kravitz como Mulher-Gato",
        "PaulDano": "Paul Dano como Charada",
        "JeffreyWright": "Jeffrey Wright como Comsisário Gordon",
        "JohnTurturro": "John Turturro como Falcone",
        "ColinFarrell": "Colin Farrell como Pinguim",
    },

    en: {
        "rodape": "ALL RIGHTS RESERVED BY DC COMICS ©",
        "tituloTestes": "TEST CATALOG",
        "menuRespostas": "ANSWERS",
        "menuContato": "CONTACT US",
        "menuInformacoes": "ABOUT",
        "tituloContato": "CONTACT US",
        "tituloPaginaPrincipal": "Winged Rat Collection",
        "tituloSugestaoMelhoriaContato": "Give us suggestions for improvement!",
        "descricaoAbaixoTituloSugestaoMelhoriaContato": "With Batman, there is no dialogue, but with us, there is. Tell us what you think!",
        "seusDadosContato": "Your Data:",
        "placeholderNome": "YOUR NAME",
        "placeholderEmail": "YOUR E-MAIL",
        "labelTituloMensagem": "Leave us a message:",
        "buttonEnviarMensagem": "Send",
        "tituloDesenvolvimentoPaginaInformacoes": "PAGE DEVELOPMENT",
        "descricaoDesenvolvimentoPagina": "The Winged Rat Collection was created with the purpose of recovering the content of the secret website featured in the movie “The Batman,” since after the film's release, the website stopped working, displaying only an image with the following phrase: “THE DOMAIN HAS BEEN SEIZED” (visit www.rataalada.com).",
        "descricaoPaginaIndexDesenvolvimento": "The home page contains the cards that, in theory, should lead to the first test and its solution. Unfortunately, it was not possible to do this, so I decided to leave it this way: just the cards.",
        "descricaoPaginaTheBatmanDesenvolvimento": "The “The Batman” page contains information about the movie “The Batman,” such as its synopsis, plot, and the cast that was part of the project. This section was created with the intention of showing where the initial idea for my website came from, as well as introducing the movie to users.",
        "descricaoPaginaRespostasDesenvolvimento": "The “Answers” page was created to have a mysterious tone. On the original movie website, as mentioned at the beginning, we are only shown an image warning us that the page has been taken over by the police of the fictional Gotham City. On my website, in the tab I describe here, I put the same image to say that it is impossible to know the answers to the tests, since the fictional police (who would be corrupt) do not want us to know the answers, as they expose an entire criminal scheme. There is no menu, since that part has already been taken over and does not “belong to me.”",
        "descricaoPaginaSobreDesenvolvimento": "Finally, the “About” page contains information about the complete development of the page, the website that was used as inspiration, and the references used for content.",
        "tituloSobreSiteOriginal": "About the original website",
        "descricaoSobreSiteOriginal": "www.rataalada.com is the name of a website used for a virtual marketing campaign for Matt Reeves' film The Batman. The website was launched on December 10, 2021, but content was only added to it on December 21, 2021. The website is in English and does not support Brazilian or European Portuguese. On December 20, 2021, a GIF image was added to DC Comics official Instagram account depicting a piece of paper with the words “let's play a game, just you and me” written on it. This is a reference to a phrase spoken by the character Riddler in the film. The next day, the website “www.rataalada.com” featured a riddle game themed around the antagonist of The Batman. The game consisted of a series of three questions where the player had to correctly answer the riddles posed by the character. Upon completion, an image of a Batman character card made by D.P.G.C. was released as a reward. Returning to the website later, the Riddler asked if the player had ever been to the Penguin's Iceberg Club. Regardless of the answers, the character states that it is best to stay away from there because the place looks more like a zoo, a reference to Batmans fight against the Penguin that takes place at the Iceberg Club in The Batman. The campaign continued until the film's opening week in March 2022, with six riddle tests and six questions about Gotham City. Finally, the last reward revealed a video about Bruce Waynes election campaign.The website was announced in the post-credits scene of The Batman movie. When accessing the website after March 5, 2022, a percentage countdown began, with all riddle games having ended. Upon reaching 100% on March 11, 2022, a file containing all the information the Riddler had collected about his main targets was made available. After the film's premiere, the website resumed operation with riddles on March 18, 2022, designed to announce a comic book written by Paul Dano, Riddler: Year One. Two more series of riddles were posted until the website was “shut down” by the D.P.G.C. at the end of the month. The website had a static background while the text was typed in green font, resembling a code reader. The website icon is the Riddler's question mark. After being taken over by the D.P.G.C., only the police logo on a blue background remained",
        "tituloReferencias": "References",
        "buttonPTBR": "Brazilian Portuguese",
        "tituloQuizFormsBatman": "🦇 QUIZ: Which Batman are you? 🦇",
        "primeiraPerguntaQuizBatman": "1. How do you deal with your feelings?",
        "segundaPerguntaQuizBatman": "2. What would be your favorite weapon as a hero?",
        "terceiraPerguntaQuizBatman": "3. What would your Batcave be like?",
        "quartaPerguntaQuizBatman": "4. How do people see you?",
        "quintaPerguntaQuizBatman": "5. Which of these phrases best describes you?",
        "sextaPerguntaQuizBatman": "6. What is your view about justice?",
        "resposta1QuizBatman": "a. I keep everything to myself and turn it into motivation", 
        "resposta2QuizBatman": "b. I try to rationalize and move on", 
        "resposta3QuizBatman": "c. I isolate myself, but feel everything intensely", 
        "resposta4QuizBatman": "d. I use sarcasm as a shield", 
        "resposta5QuizBatman": "e. I try to stay balanced and do what is right", 
        "resposta6QuizBatman": "a. Raw strength and intimidating stare", 
        "resposta7QuizBatman": "b. Cutting-edge technology and sophisticated armor", 
        "resposta8QuizBatman": "c. Agility and stealth tactics", 
        "resposta9QuizBatman": "d. Charm and improvisation", 
        "resposta10QuizBatman": "e. Discipline and training", 
        "resposta11QuizBatman": "a. Dark, gothic and full of secrets", 
        "resposta12QuizBatman": "b. Modern, functional and full of gadgets", 
        "resposta13QuizBatman": "c. Minimalist but efficient", 
        "resposta14QuizBatman": "d. A bit messy but stylish", 
        "resposta15QuizBatman": "e. Classic, with everything in order", 
        "resposta16QuizBatman": "a. Mysterious and intense", 
        "resposta17QuizBatman": "b. Serious and intelligent", 
        "resposta18QuizBatman": "c. Cold but deep", 
        "resposta19QuizBatman": "d. Charismatic and creative", 
        "resposta20QuizBatman": "e. Fair and reliable", 
        "resposta21QuizBatman": "a. \"Vengeance drives me.\"", 
        "resposta22QuizBatman": "b. \"I am Batman\"", 
        "resposta23QuizBatman": "c. \"I dont need people to like me, only to respect me.\"", 
        "resposta24QuizBatman": "d. \"Who said Batman cant have style?\"", 
        "resposta25QuizBatman": "e. \"With great power comes great responsibility\"", 
        "resposta26QuizBatman": "a. Justice is protecting innocents using intelligence.", 
        "resposta27QuizBatman": "b. Justice is eliminating evil firmly and without hesitation.", 
        "resposta28QuizBatman": "c. Justice is maintaining balance and inspiring hope.", 
        "resposta29QuizBatman": "d. Justice is confronting corruption where it truly begins.", 
        "resposta30QuizBatman": "e. Justice is being fair.",
        "tituloResultadosQuiz": "Results",
        "tituloPrimeiroResultado": "🔴 Majority A: Robert Pattinson (The Batman - 2022)",
        "tituloSegundoResultado": "🔵 Majority B: Christian Bale (The Dark Knight Trilogy - 2005 to 2012)",
        "tituloTerceiroResultado": "⚫ Majority C: Ben Affleck (Justice League, Batman vs Superman - from DCEU)",
        "tituloQuartoResultado": "🟣 Majority D: George Clooney or Val Kilmer (Batman and Robin, Batman Forever)",
        "descricaoPrimeiroResultado": "You are dark, introspective, and driven by deep emotions. You don't care what others think, because you are focused on your mission. You are still discovering yourself, but you already command respect.",
        "descricaoSegundoResultado": "You are determined, calculating, and intense. You masterfully balance your Bruce Wayne side with your Batman side. A true strategist, you play the long game.",
        "descricaoTerceiroResultado": "You are a weary but still powerful veteran. A little more bitter and cynical, you prefer action to words. You will go to any lengths if you believe you are right.",
        "descricaoQuartoResultado": "You are lighter, more stylish, and don't take yourself so seriously. Still, you have a sense of justice. You prefer to resolve issues with charm (and a Batmarca credit card,  maybe?).",
        "tituloPaginaRespostas": "Answers",
        "legendaInicialImagemBatman": "“I wish I could say I'm making a difference, but I don't know. Murders, robberies, assaults. Two years later, all of this. And now this... The city is consuming itself. Maybe there's no hope left.”",
        "tituloSinopseTheBatman": "Sinopsis",
        "descricaoSinopse": "Two years of roaming the streets as Batman (Robert Pattinson), striking fear into the hearts of criminals, have taken Bruce Wayne into the depths of Gotham City's shadows. With only a few trusted allies—Alfred Pennyworth (Andy Serkis), Lieutenant James Gordon (Jeffrey Wright)—among the corrupt network of authorities and important figures in the city, the lone vigilante established himself as the sole embodiment of vengeance among his fellow citizens. When a killer targets Gotham's elite with a series of sadistic machinations, a trail of cryptic clues sends the World's Greatest Detective on an investigation into the underworld, where he encounters characters such as Selina Kyle/aka Catwoman (Zoë Kravitz), Oswald Cobblechuck/aka the Penguin (Colin Farrell), Carmine Falcone (John Turturro), and Edward Nashton/aka the Riddler (Paul Dano). As the evidence begins to lead him closer to home and the scale of the perpetrator's plans becomes clear, Batman must forge new relationships, unmask the culprit, and bring justice to the abuse of power and corruption that have long plagued Gotham City.",
        "tituloTramaTheBatman": "PLOT",
        "descricaoTramaTheBatman": "On Halloween night, the mayor of Gotham is killed by a murderer named the Riddler, who leaves riddles for Batman. Bruce Wayne, who has been Batman for two years, investigates the case with Lieutenant Gordon. They discover that the Riddler is targeting public figures involved in corruption. Batman crosses paths with Selina Kyle (Catwoman), whose friend Annika disappeared after getting involved with corrupt politicians. Selina works at the Iceberg Lounge, controlled by Carmine Falcone, a powerful mobster who is also her father. During the investigation, District Attorney Colson is killed by the Riddler after refusing to reveal the name of an informant. The corruption revealed also involves the Wayne family's past. It is discovered that Thomas Wayne asked Falcone for help in silencing a journalist, but later wanted to redeem himself. Thomas and Martha ended up dead, and Bruce begins to suspect Falcone's involvement. Selina tries to kill Falcone for revenge, but Batman stops her. However, the Riddler murders him when he is arrested. Even after his capture, the Riddler reveals his final plan: to detonate bombs that will flood Gotham and encourage fanatical followers to kill the new mayor, Bella Reál. Batman and Selina prevent the attack, and Batman begins to act as a symbol of hope for the city. Selina decides to leave Gotham, and the two go their separate ways. Meanwhile, the Riddler finds a mysterious new ally in Arkham.",
        "tituloElencoTheBatman": "CAST",
        "RobertPattinson": "Robert Pattinson as Bruce Wayne/Batman",
        "ZoeKravitz": "Zoe Kravitz as CatWoman",
        "PaulDano": "Paul Dano as Riddler",
        "JeffreyWright": "Jeffrey Wright as Jim Gordon",
        "JohnTurturro": "John Turturro as Falcone",
        "ColinFarrell": "Colin Farrell as Penguin",
    }
};

function setLinguagem(language){ 
    sessionStorage.setItem("idioma", language)
    document.querySelectorAll("[data-i18n]").forEach(mudar => {
        const chave = mudar.getAttribute("data-i18n");
        const novoTexto = traducao[language][chave];
        mudar.textContent = novoTexto; 
    });
}

document.addEventListener("DOMContentLoaded", () => { 
    const idioma = sessionStorage.getItem("idioma") || "pt"; 
    setLinguagem(idioma); 
});